config/routes.rb
Rails.application.routes.draw do

  root to: 'drinks#index'
  get    '/login',   to: 'sessions#new'
  post    '/users/auth/:provider/callback',to: 'sessions#create'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # static_pagesのルーティング
  get    '/contact',   to: 'static_pages#contact'
  get    '/about_coffee_passport', to: 'static_pages#about_coffee_passport'
  
  get 'user/config', to: 'users#config'   ,as: 'user_config'
  get 'user/likes/:id',  to: 'users#likes',as: 'user_likes'
  get 'user/purchase_record',to: 'users#purchase_record'
  post 'users/guest_sign_in',to: 'users#new_guest'
  resources :users do
    member do
      get :following,:followers
      # memberメソッドを使うと
      # ユーザーidが含まれてるURlを扱うようになる
    end
  end
  get 'drinks/searchingform', to: 'drinks#show_searching_form'
  get '/drinks/searchdrink',  to: 'drinks#search_drink'
  get '/drink/hashtag/:name', to: "drinks#hashtag"
  resources :drinks, only: [:index,:new,:show,:create,:destroy] do
    collection do
      get 'search'
    end

    resources :comments,only: [:create,:destroy]
    # あるツイートに対してのコメントと言う
    # 親子関係を表現したパスが、コメント投稿に必要なリクエストの
    # パスになります
    
    resources :trades,only: [:index,:new,:create]
  end

  namespace :api, format: 'json' do
    resources :drinks, only: [:index,:show]
  end

  namespace :api, { format: 'json' } do
    resources :likes, only: [:index, :create, :destroy]
  end


  post '/drinks/:id/trades/new', to: 'trades#create'
  resources :relationships, only: [:create,:destroy]
  post 'like/:drink_id' ,to: 'likes#like', as: 'like'
  delete 'like/:drink_id',to: 'likes#unlike', as: 'unlike'
  resources :account_activations, only: [:edit]
  get '/buy', to: 'sold_drinks#index'
  get '/sort_cheap_order', to: "sold_drinks#sort_cheap_order"
  get '/sort_often_purchased_order', to: "sold_drinks#sort_often_purchased_order"
end

app/models/drink.rb
class Drink < ApplicationRecord
  attr_accessor :region_name ,:acidity_name,:body_name ,:processing_name
  # json形式でvueの方にカテゴリーを渡すためにカテゴリーの属性を定義
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many :trades
  has_many :drink_tag_relations, dependent: :delete_all
  has_many :tags, through: :drink_tag_relations
  has_many :comments
  has_many :likes
  has_many :liking_users, through: :likes, source: :user
  has_one_attached :image
  belongs_to_active_hash :region
  belongs_to_active_hash :body
  belongs_to_active_hash :acidity
  belongs_to_active_hash :processing
  with_options presence: true do
    validates :name, length: { maximum: 1000 }
    validates :explain, length: { maximum: 1000 }
    validates :image
    validates :price, format: { with: /\A[0-9]+\z/i }
  end

  after_create do
    drink = Drink.find_by(id: id)
    # 作成した投稿を探させます
    # binding.pry
    hashtags = explain.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    # 先頭に#がつく入力値を,drinkのexplainから
    # 探し抽出します
    drink.tags = []
    hashtags.uniq.map do |hashtag|
      # ハッシュタグは先頭の#を外した上で保存
      # uniqは配列から重複した要素を取り除いた新しい配列を返すメソッド
      # mapは配列の要素の数だけ繰り返し処理を行うメソッドです。
      tag = Tag.find_or_create_by(tag_name: hashtag.downcase.delete('#'))
      # ハッシュタグがすでに存在してるかを調べ、なければ作成
      drink.tags << tag
    end
  end

  # 更新アクション

  before_update do
    drink = Drink.find_by(id: id)
    # hashbodyに打ち込まれたハッシュタグを検出
    hashtags = explain.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    drink.tags = []
    hashtags.uniq.map do |hashtag|
      # ハッシュタグは先頭の#を外した上で保存
      self.add_emozi(hashtag)
      tag = Tag.find_or_create_by(tag_name: hashtag.downcase.delete('#'))
      drink.tags << tag
    end
  end


end

app/controllers/api/drinks_controller.rb
class Api::DrinksController < ApplicationController

  include SessionsHelper

  def index
    def index
      @user = current_user
  
      following_ids = 'SELECT followed_id FROM relationships WHERE follower_id = :user_id'
      
      @drinks = Drink.includes(:user ,{image_attachment: :blob})
                     .where.not(user_id: 6)
                     .where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: @user.id)
                     .order('drinks.created_at DESC')
    end
  end


  def show
    @drink = Drink.find(params[:id])
    #@user = @drink.user
    #@comment = Comment.new
   # @comments = @drink.comments.includes(:user).order('created_at DESC')
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  include SessionsHelper
  include Pagy::Backend


  before_action :logged_in_user, only: [:index, :new, :destroy]
  before_action :create_searching_object, only: [:show_searching_form, :search_drink]

  def index
     # 購入履歴に応じたおすすめのコーヒーや
     # ランダムに投稿を表示する機能を定義するメソッド

    @user = current_user

    @num = rand(0..1)
    # 命名が酷いのでなにかいい命名あったらお願いします。
    # この変数は、ユーザーの好みの酸味もしくは、
    # コクをできるだけ交互におすすめするために、定義しました。
    
    drink_body_ids = []
    drink_acidity_ids = []

    if @user.trade_drinks
      @user.trade_drinks.each do |drink|
        drink_body_ids << drink.body_id 
        drink_acidity_ids << drink.acidity_id
      end

      unless drink_body_ids == []

        @favorite_body_id = drink_body_ids.group_by{|e| e}.max_by{|v| v.size}.first
      end

      unless drink_acidity_ids == []
        
        @favorite_acidity_id = drink_acidity_ids.group_by{|e| e}.max_by{|v| v.size}.first
        
      end

    

      # https://osa.hatenablog.com/entry/2014/12/21/122603
      # max_byは最大のものを返すMethod
      # 今回は要素数が最大のものを返す v.sizeで要素数を比較するようにしてる
      
  
     
    end

    
    if @num == 0
    @pagy,@drinks = pagy(Drink.includes(:user ,{image_attachment: :blob})
                    .where(body_id: @favorite_body_id)
                    .order('drinks.created_at DESC'))
    else
      @pagy,@drinks = pagy(Drink.includes(:user ,{image_attachment: :blob})
      .where(acidity_id: @favorite_acidity_id)
      .order('drinks.created_at DESC'))
    end

    @title = 'おすすめのコーヒー'

    @selected = 'Selected'

    @random_drinks = Drink.includes(:user, {image_attachment: :blob}).order('RAND()').limit(5)

  end

  def show
    @drink = Drink.find(params[:id])
    @user = @drink.user
    @comment = Comment.new
    @comments = @drink.comments.includes(:user).order('created_at DESC')
  end

  def new
    @drink = Drink.new
  end

  def create
    @drink = Drink.new(drink_params)
    if @drink.valid?
      @drink.save
      # binding.pry
      redirect_to drinks_path
    else
      render 'new'
    end
  end

  def destroy
    Drink.find(params[:id]).destroy
    redirect_to current_user
  end

  # GET search
  def search
    return nil if params[:keyword] == ''

    # 何も入れず検索したらエラーが起こるので、
    # 明示的にnilを返す
    tag = Tag.where(['tag_name LIKE ?', "%#{params[:keyword]}%"])
    # 第二引数が第一引数の?に入っていく,検索した
    # タグがデータベースにあれば返す
    render json: { keyword: tag }
    # const tagName = XHR.response.keyword
    # の.keywordが使えてる
  end

  def search_drink
    @results = @p.result

    # binding.pry
  end

  def show_searching_form
  end

  def hashtag
    @user = current_user
    if @tag = Tag.find_by(tag_name: params[:name])
      @pagy,@drinks = pagy(@tag.drinks.order('created_at DESC'))
      @title = "##{@tag.tag_name}"
    else
      render 'drinks/_not_found'
    end
  end

  private

  def drink_params
    params.require(:drink).permit(:name, :price, :explain, :image, :tag_name, :region_id, :body_id, :body, :acidity_id,
                                  :processing_id).merge(user_id: current_user.id)
  end

  def create_searching_object
    @p = Drink.ransack(params[:q])
  end
end

app/helpers/api/drinks_helper.rb
module Api::DrinksHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

def render_with_hashtags(caption)
  caption.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) { |word| link_to word, "/drink/hashtag/#{word.delete('#')}" }.html_safe
  # リンク付きのハッシュタグが入ったキャプション(説明)が作成されます
 
  #add_emozi(@hashtag)

  # gsubメソッドは、文字列中で、パターンにマッチする
  # 部分を全て文字列で置き換えた文字列を生成して返します。

  # 先頭にハッシュタグがついてる文字列を
  # リンクに変えて、それ以外は何もしない

  #.html_safeメソッドは、HTML語の文字をそのまま出力してしまう
  # HTML語に変換してもらうためのメソッド
  # 例) .html_safeがなかったら<a>hogehoge<a>
  # と文字列がそのまま出力される
  # .html_safeを付けたら、意味を読み取ってくれて,リンク化してくれる
end

def add_emozi(hashtag)
 
  case hashtag
  when "#COCOA"
    hashtag = hashtag + "ha"
   # binding.pr
  end
end

app/views/drinks/_drinks.html.erb
<div class='show-main'>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'></h2>
    <ul class='item-lists'>
      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <%if @drink%>
      <li class='list'>
        <%= link_to drink_path(@drink.id) do %>
        <div class='item-img-content'>
          <%= image_tag @drink.image , class: "item-img" if @drink.image.attached? %>
          
          <%# if drink.trade%>
          
   
          
          <%# end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= @drink.name %>
          </h3>
          <div class='item-price'>
            <span><%= @drink.price %>円<br>(税込み)</span>
          </div>
          <div class='item-explain'>
             <%= render_with_hashtags(@drink.explain) %>
          </div>

          <%# ここから%>
          <table class="item-category">
            <tbody>
              <tr class="item-region">
                <% if @drink.region %>
                  <th class="region-title">産地 </th>
                   <td class="region-name"><%= @drink.region.name%> </td>             
                <% end %>
              </tr>
                <tr class="item-body">
                  <% if @drink.body%>
                  <th class="body-title">コク</th> 
                  <td class="body-name"><%= @drink.body.name %></td>
                  <% end %>
                </tr>
                <tr class="item-acidity">
                  <% if @drink.acidity %>
                    <th class="acidity-title">酸味</th> 
                    <td class="acidity-name"><%= @drink.acidity.name%></td>
                  <% end %>
                </tr>
                <tr class="item-processing">
                  <% if @drink.processing%>
                    <th class="processing-title">加工法</th>
                     <td class="processing-name"><%= @drink.processing.name%></td>
                  <% end %>
                </tr>
              
            </tbody>
          </table>
           <%= render "likes/like",drink: @drink%>
        </div>
        <% if logged_in? && current_user.id == @drink.user_id %>
        <div class="item-delete">
          <%= link_to "削除する",drink_path(@drink),method: :delete,data: {confirm: "本当に削除しますか？"} %>
        </div>

        <% end %>
            <%if @drink.user.id == 6%>
            <%= link_to "商品を購入する",drink_trades_path(@drink.id),class: "buy-link"%>
            <%end%>
      </li>
      <%end%>
    </ul>

    <div class="comment-container">
      <div id="comments-create">
        <%= render partial: 'comments/create', locals: {comment: @comment, drink: @drink} %>
      </div>
    </div>

    <div id="comments-index">
       <%= render partial: 'comments/index', locals: {comments: @comments,drink: @drink} %>
    </div>  

  </div>
  
  <%end%>

  </div>
</div>

app/views/drinks/_drinks_index.html.erb
<div class='main'>
 
  <%# 商品一覧 %>
  <div class='item-contents'>
   
        <h2 class='title'><%=title%></h2>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <%if drinks %>
      
        <% drinks.each do |drink|%>
        <li class='list'>
          
          <%unless drink.user.id == 6%>
            <%= link_to user_path(drink.user.id) do%>
              <div class="user-info-timeline">
                  <% if drink.user.image.attached?%>
                    <%=image_tag drink.user.image.variant(resize: '60x60'),class: "user-img-timeline"  %> 
                  <% else %>
                   <img src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YnJlYXV0aWZ1bCUyMGdpcmx8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60" class= 'user-img-timeline'>
                  <% end %>
                  <div class="username-timeline">
                    <%= drink.user.nickname %>
                  </div>
              </div>
            <% end %>
          <%end%>

          
            <div class='item-img-content'>
              <%= link_to drink_path(drink.id) do %>
              <%= image_tag drink.image , class: "item-img" if drink.image.attached? %>
              
            </div>
            <div class='item-info'>
              <h3 class="item-name"> 
                <%= drink.name %>
              </h3>
              <div class='item-price'>
                <span><%= drink.price %>円<br>(税込み)</span>
              </div>
              <div class='item-explain'>
              <%= render_with_hashtags(drink.explain.truncate(24, separator: /\s/)) %>
                <%#= drink.explain .truncate(24, separator: /\s/) %>
              </div>
              <div class='item-tag'>
              <%# drink.tags.each do |tag| %>
                  
                <%#end%> 

              </div>
              <div class="like-and-comment">
                 <%= render "likes/like",drink: drink%>
                 <%= link_to drink_path(drink.id) do%>
                 <i class="far fa-comment fa-lg"></i>
                 <% end %>
              </div>
            <% end %>
            </div>
            <%#ここにラベルを追加%>

            
            <%case drink.body.id
              when 2%>
            <%# コーヒーのコクが軽い場合%>
            <div class="body-light"></div>
            <%when 3%>
            <%# コーヒーのコクが程よい場合%>
            <div class="body-medium"></div>
            <%when 4%>
            <%# コーヒーのコクがしっかりしてる場合%>
            <div class="body-full"></div>
            <% else %>
            <%# コーヒーのコクが登録されてない場合%>
            <div class="body-nothing"></div>
            <% end %>

            <%case drink.acidity.id
             when 2%>
            <%# コーヒーの酸味が場合%>
            <div class="acidity-low"></div>
            <%when 3%>
            <%# コーヒーの酸味が程よい場合%>
            <div class="acidity-medium"></div>
            <%when 4%>
            <%# コーヒーの酸味が強い場合%>
            <div class="acidity-high"></div>
            <% else %>
            <div class="acidity-nothing"></div>
            <% end %>
            

            <%if drink.user.id == 6%>
            <%= link_to "商品を購入する",drink_trades_path(drink.id),class: "buy-link"%>
            <%end%>

            <% if drink.trades_count%>
              <%= "#{drink.trades_count}回購入されてます。"%>
            <% end %>
        </li>
      
 
      <%end%>

      </ul> 
      </div>
    <%end%>
</div>
<%== pagy_nav(@pagy) %>

app/views/drinks/_not_found.html.erb
  <div class="not-found">
  <p>Sorry：(</p>
  <i class="far fa-sad-tear"></i>
    <p>該当する商品はありません</p>
    <%= link_to 'トップページへ戻る', root_path ,class: "root_path"%>
  </div>

app/views/drinks/hashtag.html.erb
<% provide(:title,@tag.tag_name)%>

<%= render 'drinks_index',drink: @drink, drinks: @drinks,title: @title%>

app/views/drinks/index.html.erb
<script>
var user = <%= { id: current_user.try(:id) }.to_json.html_safe %>;

</script>

<%= javascript_pack_tag 'hello_vue' %>

<% provide(:title,"Home")%>


  <p class="suggest-coffee-explain">購入履歴に応じておすすめされます</p>
<div class="suggest-coffee-title">
  <% if @num == 0%>
    <% case @favorite_body_id 
      when 2%>
    浅煎りのコーヒーが好きなあなたに
    <% when 3%>
    中煎りのコーヒーが好きなあなたに
    <% when 4%>
    深煎りのコーヒーが好きなあなたに
    <% end %>
  <% else %>
    <% case @favorite_acidity_id 
      when 2%>
    酸味が少ないのコーヒーが好きなあなたに
    <% when 3%>
    ほどよい酸味のコーヒーが好きなあなたに
    <% when 4%>
    酸味が強いコーヒーが好きなあなたに
    <% end %>
  <% end %>
</div>
<%= render 'drinks_index',drink: @drink, drinks: @drinks,title: @title%> 




<%# ピックアップ投稿 %>
    

<div class='main'>

  <%# 商品一覧 %>
  <div class='item-contents'>
   
    <%if @selected%>
      <h2 class="title"><%= @selected%></h2>
      <p>ランダムに投稿が表示されます</p>
    <% end %>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <%if @random_drinks %>
      
        <% @random_drinks.each do |drink|%>
        <li class='list'>
          
          <%unless drink.user.id == 6%>
            <%= link_to user_path(drink.user.id) do%>
              <div class="user-info-timeline">
                  <% if drink.user.image.attached?%>
                    <%=image_tag drink.user.image.variant(resize: '60x60'),class: "user-img-timeline"  %> 
                  <% else %>
                   <img src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YnJlYXV0aWZ1bCUyMGdpcmx8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60" class= 'user-img-timeline'>
                  <% end %>
                  <div class="username-timeline">
                    <%= drink.user.nickname %>
                  </div>
              </div>
            <% end %>
          <%end%>

            <div class='item-img-content'>
              <%= link_to drink_path(drink.id) do %>
              <%= image_tag drink.image , class: "item-img" if drink.image.attached? %>
              
            </div>
            <div class='item-info'>
              <h3 class="item-name"> 
                <%= drink.name %>
              </h3>
              <div class='item-price'>
                <span><%= drink.price %>円<br>(税込み)</span>
              </div>
              <div class='item-explain'>
              <%= render_with_hashtags(drink.explain.truncate(24, separator: /\s/)) %>
                <%#= drink.explain .truncate(24, separator: /\s/) %>
              </div>
              <div class='item-tag'>
              <%# drink.tags.each do |tag| %>
                  
                <%#end%> 

              </div>
              <div class="like-and-comment">
                 <%= render "likes/like",drink: drink%>
                 <%= link_to drink_path(drink.id) do%>
                 <i class="far fa-comment fa-lg"></i>
                 <% end %>
              </div>
            <% end %>
            </div>
            <%if drink.user.id == 6%>
            <%= link_to "商品を購入する",drink_trades_path(drink.id),class: "buy-link"%>
            <%end%>

            <%case drink.body.id
              when 2%>
            <%# コーヒーのコクが軽い場合%>
            <div class="body-light"></div>
            <%when 3%>
            <%# コーヒーのコクが程よい場合%>
            <div class="body-medium"></div>
            <%when 4%>
            <%# コーヒーのコクがしっかりしてる場合%>
            <div class="body-full"></div>
            <% else %>
            <%# コーヒーのコクが登録されてない場合%>
            <div class="body-nothing"></div>
            <% end %>

            <%case drink.acidity.id
             when 2%>
            <%# コーヒーの酸味が場合%>
            <div class="acidity-low"></div>
            <%when 3%>
            <%# コーヒーの酸味が程よい場合%>
            <div class="acidity-medium"></div>
            <%when 4%>
            <%# コーヒーの酸味が強い場合%>
            <div class="acidity-high"></div>
            <% else %>
            <div class="acidity-nothing"></div>
            <% end %>
        </li>

 
      <%end%>

      </ul> 
      </div>
    <%end%>
</div>

app/views/drinks/new.html.erb
<% provide(:title,"Post")%>
<div class="slideshow">
<div class="items-sell-contents">

  <div class="items-sell-main">
    <h2 class="items-sell-title">コーヒーの記録</h2>
    <%= form_with model: @drink,url: drinks_path, local: true do |f| %>


    <%= render 'shared/error_messages', object: f.object %>
    
    <div class="tag-field" , id='tag-field'>
      <%# <div class="weight-bold-text">
        #タグ付け <%#= f.text_field :tag_name,class: "post-tag" %>
  
    </div>
    <div id="search-result">
    </div>
    <div class="img-upload">
      <div class="weight-bold-text">
        写真
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image %>
        <div id="image-list"></div>
      </div>
    </div>
    
    <div class="new-items">
      <div class="weight-bold-text">
        コーヒー名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          感想
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explain, class:"items-text", id:"item-info", placeholder:"コーヒーの感想（ハッシュタグ(#)をつけて投稿できます）",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="price-content">
      <div class="price-text">
        <span>価格</span>
        <span class="indispensable">必須</span>
      </div>
        <span class="sell-yen">¥</span>
      <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例） 1000" %>円
    </div>

    <div class="post-category">
      (分かる場合はできるだけ書きましょう)
      <div class="post-region">
        <p> 地域</p>
        <%= f.collection_select(:region_id,Region.all,:id,:name,{},{class: "select-box"})%>
      </div>
      <div class="post-body">
        <p>コク</p>
        <%= f.collection_select(:body_id,Body.all,:id,:name,{},{class: "select-box"})%>
      </div>
      <div class="post-acidity">
        <p>酸味</p>
        <%= f.collection_select(:acidity_id,Acidity.all,:id,:name,{},{class: "select-box"})%>
      </div>
      <div class="post-processing">
        <p>加工法</p>
        <%= f.collection_select(:processing_id,Processing.all,:id,:name,{},{class: "select-box"})%>
        <br>
        <%= link_to "加工法についてもっと詳しく","#"%>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

  </div>
  <% end %>
</div>

app/views/drinks/search_drink.html.erb
<% provide(:title,"検索結果")%>
<%# 検索結果の個数で条件分岐 %>
<% if @results.length !=0 %>

<%  @results.each do |drink| %>
  <div class='main'>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'></h2>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <%if drink%>
      <li class='list'>
        <%= link_to drink_path(drink.id) do %>
        <div class='item-img-content'>
          <%= image_tag drink.image , class: "item-img" if drink.image.attached? %>
          
          <%# if drink.trade%>
          
   
          
          <%# end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= drink.name %>
          </h3>
          <div class='item-price'>
            <span><%= drink.price %>円<br>(税込み)</span>
          </div>
          <div class='item-explain'>
            <%= drink.explain.truncate(24, separator: /\s/) %>
          </div>
          <div>
            <% if drink.region %>
            産地 <%= drink.region.name%>              
            <% end %>
          </div>
          <div>
            <% if drink.body%>
            コク <%= drink.body.name %>
            <% end %>
          </div>
          <div>
            <% if drink.acidity %>
              酸味 <%= drink.acidity.name%>
            <% end %>
          </div>
          <div>
            <% if drink.processing%>
              加工法 <%= drink.processing.name%>
            <% end %>
          </div>
        </div>
        <% if logged_in? && current_user.id == drink.user_id %>
        <div class="item-delete">
          <%= link_to "削除する",drink_path(drink),method: :delete %>
        </div>
        <% if drink.trade%>
        <%= link_to "商品を購入する", drink_trades_path(drink) %>
        <% end %>
        <% end %>

            <%case drink.body.id
              when 2%>
            <%# コーヒーのコクが軽い場合%>
            <div class="body-light"></div>
            <%when 3%>
            <%# コーヒーのコクが程よい場合%>
            <div class="body-medium"></div>
            <%when 4%>
            <%# コーヒーのコクがしっかりしてる場合%>
            <div class="body-full"></div>
            <% else %>
            <%# コーヒーのコクが登録されてない場合%>
            <div class="body-nothing"></div>
            <% end %>

            <%case drink.acidity.id
             when 2%>
            <%# コーヒーの酸味が場合%>
            <div class="acidity-low"></div>
            <%when 3%>
            <%# コーヒーの酸味が程よい場合%>
            <div class="acidity-medium"></div>
            <%when 4%>
            <%# コーヒーの酸味が強い場合%>
            <div class="acidity-high"></div>
            <% else %>
            <div class="acidity-nothing"></div>
            <% end %>
      </li>
      <%end%>
     
        
      

    </ul>
  </div>
  <%end%>
</div>

<% end %>

<% else %>

<%= render 'not_found'%>

<% end %>

app/views/drinks/show.html.erb
<% provide(:title,"Details")%>
<%= render "drinks/drinks",drink: @drink%>

app/views/drinks/show_searching_form.html.erb
<% provide(:title,"検索")%>

<div class="searching-form">

  <%= search_form_for @p, url: drinks_searchdrink_path do |f| %>
    <div class="searching-by-name">
      <h3 class="name-label"><i class="fas fa-search"></i>名前で検索</h3>
      <%= f.search_field :name_cont,placeholder: "検索"%>
      <div id="search-result">
      </div>
    </div>


      <h3 class="category-font">カテゴリー検索</h3>
      <div class="region">
        <%= f.label '地域' ,class: "select-label"%>
        <%= f.collection_select :region_id_eq, Region.all ,:id, :name ,{include_blank: '地域を選択' },{class: "select-box"} %>
      </div>

      <%# ベースはドリンククラスで、第二引数で%>
      <br>
      <div class="body">
        <%= f.label 'コク',class: "select-label"%>
        <%= f.collection_select :body_id_eq,Body.all,:id,:name,{include_blank: 'コクを選択'} ,{class: "select-box"}%>
      </div>
      <br>
      <div class="acidity">
        <%= f.label '酸味',class: "select-label"%>
        <%= f.collection_select :acidity_id_eq,Acidity.all,:id,:name,{include_blank: '酸味を選択'},{class: "select-box"} %>
      </div>
      <br>
      <div class="processing">
        <%= f.label '加工法',class: "select-label"%>
        <%= f.collection_select :processing_id_eq,Processing.all,:id,:name,{include_blank: '加工法を選択'},{class: "select-box-processing"} %>
      </div>
        <%= f.submit '検索' ,class: "searching-submit-btn"%>
  <% end %>

</div>