config/routes.rb
Rails.application.routes.draw do

  root to: 'drinks#index'
  get    '/login',   to: 'sessions#new'
  post    '/users/auth/:provider/callback',to: 'sessions#create'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # static_pagesのルーティング
  get    '/contact',   to: 'static_pages#contact'
  get    '/about_coffee_passport', to: 'static_pages#about_coffee_passport'
  
  get 'user/config', to: 'users#config'   ,as: 'user_config'
  get 'user/likes/:id',  to: 'users#likes',as: 'user_likes'
  get 'user/purchase_record',to: 'users#purchase_record'
  post 'users/guest_sign_in',to: 'users#new_guest'
  resources :users do
    member do
      get :following,:followers
      # memberメソッドを使うと
      # ユーザーidが含まれてるURlを扱うようになる
    end
  end
  get 'drinks/searchingform', to: 'drinks#show_searching_form'
  get '/drinks/searchdrink',  to: 'drinks#search_drink'
  get '/drink/hashtag/:name', to: "drinks#hashtag"
  resources :drinks, only: [:index,:new,:show,:create,:destroy] do
    collection do
      get 'search'
    end

    resources :comments,only: [:create,:destroy]
    # あるツイートに対してのコメントと言う
    # 親子関係を表現したパスが、コメント投稿に必要なリクエストの
    # パスになります
    
    resources :trades,only: [:index,:new,:create]
  end

  namespace :api, format: 'json' do
    resources :drinks, only: [:index,:show]
  end

  namespace :api, { format: 'json' } do
    resources :likes, only: [:index, :create, :destroy]
  end


  post '/drinks/:id/trades/new', to: 'trades#create'
  resources :relationships, only: [:create,:destroy]
  post 'like/:drink_id' ,to: 'likes#like', as: 'like'
  delete 'like/:drink_id',to: 'likes#unlike', as: 'unlike'
  resources :account_activations, only: [:edit]
  get '/buy', to: 'sold_drinks#index'
  get '/sort_cheap_order', to: "sold_drinks#sort_cheap_order"
  get '/sort_often_purchased_order', to: "sold_drinks#sort_often_purchased_order"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :drink, counter_cache: :likes_count
# デフォルトでは親モデル_countに値が入るが、ここではカラム名を指定してる
# 取得したN件のdrinkに対して,一つひとつcountクエリが実行されないように設定
# N+1問題を解決するためのオプション
# これの上位互換のcounter_cultureといったgemもあるから
# 余裕があればやっとこう


  scope :filter_by_drink, ->(drink_id) { where(drink_id: drink_id) if drink_id }
end

app/controllers/api/likes_controller.rb
class Api::LikesController < ApplicationController

  before_action :set_variables, only: [:create,:destroy]

  def index
    # その投稿のいいね一覧を取得
    render json: Like.filter_by_drink(params[:drink_id]).select(:id, :user_id, :drink_id)
  end

  def create
    @like = @user.likes.new(drink_id: @drink.id)
    @like.save
    head :created
  end

  def destroy
    @like = @user.likes.find_by(drink_id: @drink.id)
    @like.destroy
    head :ok
  end

  private

    def set_variables
      @user = User.find(params[:user_id])
      @drink = Drink.find(params[:drink_id])
    end

    def likes_params
      params.require(:like).permit(:drink_id)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include SessionsHelper

  before_action :set_variables

  def like
    current_user.likes.new(drink_id: @drink.id).save
    # redirect_to drinks_path
    # jsを用いるので画面遷移は行わない
    # binding.pry
    #=> like.js.erbに遷移する。
  end

  def unlike
     current_user.likes.find_by(drink_id: @drink.id).destroy
    # binding.pry
  end

  private

  def set_variables
    @drink = Drink.find(params[:drink_id])
    @id_name = "#like-link-#{@drink.id}"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div class="like" id="like-link-<%= drink.id %>">
  <% if current_user.likes.find_by(drink_id: drink.id) %>
    <%= link_to unlike_path(drink.id), method: :delete, remote: true do %>
        <div class = "iine__button">
          <i class="fas fa-heart"></i>
          <%= drink.likes.count %>
        </div>
    <% end %>
  <% else %>
    <%= link_to like_path(drink.id), method: :post, remote: true do %>
        <div class = "iine__button">
          <i class="far fa-heart">
          </i><%= drink.likes.count %>
        </div>
    <% end %>
  <% end %>
</div>

<script>
var user = <%= { id: current_user.try(:id) }.to_json.html_safe %>;
var drink = <%= { id: drink.try(:id) }.to_json.html_safe %>;
</script>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", drink: @drink  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", drink: @drink  )) %>');