config/routes.rb
Rails.application.routes.draw do

  root to: 'drinks#index'
  get    '/login',   to: 'sessions#new'
  post    '/users/auth/:provider/callback',to: 'sessions#create'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # static_pagesのルーティング
  get    '/contact',   to: 'static_pages#contact'
  get    '/about_coffee_passport', to: 'static_pages#about_coffee_passport'
  
  get 'user/config', to: 'users#config'   ,as: 'user_config'
  get 'user/likes/:id',  to: 'users#likes',as: 'user_likes'
  get 'user/purchase_record',to: 'users#purchase_record'
  post 'users/guest_sign_in',to: 'users#new_guest'
  resources :users do
    member do
      get :following,:followers
      # memberメソッドを使うと
      # ユーザーidが含まれてるURlを扱うようになる
    end
  end
  get 'drinks/searchingform', to: 'drinks#show_searching_form'
  get '/drinks/searchdrink',  to: 'drinks#search_drink'
  get '/drink/hashtag/:name', to: "drinks#hashtag"
  resources :drinks, only: [:index,:new,:show,:create,:destroy] do
    collection do
      get 'search'
    end

    resources :comments,only: [:create,:destroy]
    # あるツイートに対してのコメントと言う
    # 親子関係を表現したパスが、コメント投稿に必要なリクエストの
    # パスになります
    
    resources :trades,only: [:index,:new,:create]
  end

  namespace :api, format: 'json' do
    resources :drinks, only: [:index,:show]
  end

  namespace :api, { format: 'json' } do
    resources :likes, only: [:index, :create, :destroy]
  end


  post '/drinks/:id/trades/new', to: 'trades#create'
  resources :relationships, only: [:create,:destroy]
  post 'like/:drink_id' ,to: 'likes#like', as: 'like'
  delete 'like/:drink_id',to: 'likes#unlike', as: 'unlike'
  resources :account_activations, only: [:edit]
  get '/buy', to: 'sold_drinks#index'
  get '/sort_cheap_order', to: "sold_drinks#sort_cheap_order"
  get '/sort_often_purchased_order', to: "sold_drinks#sort_often_purchased_order"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token

  before_save   :downcase_email
  before_create :create_activation_digest
  # remember_tokenというメソッドを作成
  # password,password_comfirmationみたいな
  # 変数のように扱える
  # u.remember_token的なことができる
  has_many :drinks, dependent: :delete_all
  has_many :trades
  has_many :trade_drinks, through: :trades, source: :drink
  has_many :comments
  # followerがフォローする
  # followedがフォローされるって大原則
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  # active_relationshipってクラスも、外部キーもないので
  # 明示的に書く必要がある

  # フォローしてるユーザーをfollower_idという外部キーを
  # 使って特定しなくてはなりません

  # relationshipモデルのfollower_idにuser_idを格納する宣言

  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy

  has_many :following, through: :active_relationships,
                       source: :followed
  # followedsとかだと英語として不適切
  # souurce: で「following配列の元はfollowed id の集合」
  # ってことを明示的にrailsに伝えます
  # 「自分が」フォローしてる人
  has_many :followers, through: :passive_relationships,
                       source: :follower
  # sourceは省略してもいい、
  # rails が自動的に単数系にして、外部キーfollower_id
  # を探してくれるから
  # 「自分を」フォローしてる人
  has_many :likes
  has_many :like_drinks, through: :likes, source: :drink
  # has_many :sns_credentials
  has_one_attached :image
  has_one :address
  has_one :suggest

  before_save { self.email = email.downcase }
  has_secure_password
  validates :nickname, presence: true, length: { maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # ユーザー更新時に空のパスワードでも大丈夫
  # has_secure_passwordの方でpasswordの存在性を検証するから大丈夫
  #   validates :username, presence: true, unless: :uid? #他省略
  # validates :email, presence: true, unless: :uid?
  # has_secure_password validations: false
  # validates :password, presence: true, unless: :uid?

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的にログインするためにトークンをDBに保存
  def remember
    self.remember_token = User.new_token
    # 何のトークンか分かりやすいから
    # remember_tokenって名前を作った
    update_attribute(:remember_digest, User.digest(remember_token))
    # ハッシュ化したトークンをremember_digestに保存
  end

  # 渡されたトークンがダイジェストと一致したらtrue
  # を返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    # 二種類のブラウザを使用してログアウトした場合
    # cookiesのremember_tokenはあるけど、
    # サーバー側でremember_digestをnilにしてるから
    # nilに対して.is_password?とかやるとfor nil classエラーが起きちゃう
    # remember_digestがnilの場合はfalseを返して、処理を止める

    # 後置if文に当てはまる条件があれば処理を止めて！
    # って場合はreturnとかで明示的に書くとif ~ else ~ end
    # とか書かなくて済む
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # selfを省略してる
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # いいねしてるかどうか確かめるメソッド
  def liked_by?(drink_id)
    likes.where(drink_id: drink_id).exists?
  end

  # 外部APIからのユーザー情報を取得
  def self.find_or_create_from_auth(auth)
    # binding.pry
    provider = auth[:provider]
    uid = auth[:uid]
    nickname = auth[:info][:name]
    image = auth[:info][:image]
    # 必要に応じて情報追加してください

    # ユーザはSNSで登録情報を変更するかもしれので、毎回データベースの情報も更新する
    find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = name
      user.image_path = image
    end
  end

  def downcase_email
    self.email = email.downcase
  end

  # ユーザーにトークン情報と、ダイジェストを入れる
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    Rails.logger.debug { Rails.application.config.action_mailer.smtp_settings }
    UserMailer.account_activation(self).deliver_now
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @drinks = @user.drinks.order('created_at DESC').includes(image_attachment: :blob)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :set_user, only: [:show, :edit, :update, :correct_user]
  before_action :logged_in_user, only: [:index, :edit, :update, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :check_guest, only: :destroy

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
     #@user.send_activation_email

      #flash[:info] = 'メールをチェックしてアカウントを有効化してください.'
      @user.activate
      log_in @user
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @pagy,@drinks = pagy(@user.drinks.order('created_at DESC').includes(image_attachment: :blob))
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    # binding.pry
    user.destroy
    redirect_to root_url
  end

  def following
    # フォローしてるユーザーの表示
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    # フォロワーの表示
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  def likes
    @user = User.find(params[:id])
    @pagy,@drinks = pagy(@user.like_drinks.order('created_at DESC').includes(:user,{image_attachment: :blob}))
    @title = "#{@user.nickname}がいいねした投稿"
  end

  def purchase_record
    trades = Trade.where(user_id: current_user.id).select(:drink_id)
    # ユーザーが購入してればtradeにそのuser_idがある
    # まずはそれを取得
    # そこから、drink_idを取得

    # この時点では同じ商品も取得できてる

    # binding.pry

    @pagy,@drinks = pagy(Drink.where(id: trades).order('created_at DESC'))
    # この書き方だと同じ商品を購入できても、一つしか表示されない
    # .orderもdrinksのidを降順にしただけで、購入した順番ではない
    # binding.pry
  end

  def user_config
    redirect_to 'config'
  end

  def new_guest
    user = User.find_or_create_by(id:5 ,email: 'guest@example.com') 
      # guest@example.com
      # って登録されたらバリデーション エラーが起こる
      # 先にゲストは登録しておく必要がある
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    log_in user
    redirect_to root_path
  end

  def thanks_for_contacting
    @user = current_user
    redirect_to 'thanks.html.erb'
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    redirect_to(root_url) unless current_user?(@user)
  end

  def check_guest
    redirect_to root_path if current_user.email == 'guest@example.com'
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<div class="follow-btn">
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%# active_relationの外部キーはfollowerなので.buildをやればいいが、
  followed_idに自分のidを含めて、カラムを埋めてく %>
  <i class="fas fa-user-plus"></i><%= f.submit "Follow",class: "follow-submit" %>
<% end %>
</div>

app/views/users/_unfollow.html.erb
<div class= "follow-btn">
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
            html: { method: :delete }, remote: true) do |f| %>
  <i class="fas fa-user-minus"></i><%= f.submit "Unfollow",class: "unfollow-submit"%>
<% end %>
</div>

app/views/users/_user.html.erb
<div class="followings-followers">
<%if user.image.attached?%>
  <%=image_tag user.image   %>
<% else %>
<img src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YnJlYXV0aWZ1bCUyMGdpcmx8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60" >
<% end %>
  <%= link_to user.nickname, user %>
</div>

app/views/users/config.html.erb
<% provide(:title,"Config")%>
<div class="user-config">
  <div class="user-config-child">
    <%= link_to "ログアウト", "/logout",method: :delete,data: {confirm: "本当にログアウトしますか？"} %>
  </div>
  <div class="user-config-child">
    <%= link_to "アカウントを削除", user_path(current_user),method: :delete ,data: {confirm: "本当にアカウントを削除しますか？"}%>
  </div>

 
</div>

app/views/users/edit.html.erb
<% provide(:title,"Edit")%>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class='main'>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>フォローしてるユーザー</h2>
    <%# link_to '新規投稿商品', "#", class: "subtitle" %>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <%if @users%>
          <% @users.each do |user|%>
          <li class='list'>
            <%= link_to user_path(user.id) do %>
            <div class='item-img-content'>
              <%= image_tag user.image , class: "item-img" if user.image.attached? %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= user.nickname %>
              </h3>
            </div>
            <% end %>
          </li>
          <% end %>
      <%end%>
     
    </ul>
  </div>
  <%#end%>
</div>

<%= link_to "トップページ", root_path %>

app/views/users/likes.html.erb
<% provide(:title,"Likes")%>
<%= render 'drinks/drinks_index',drink: @drink,drinks: @drinks,title: @title%>

app/views/users/new.html.erb
<% provide(:title,"Signin")%>
<%= render "shared/form"%>

app/views/users/purchase_record.html.erb
<% provide(:title,"Purchase record")%>
<%= render 'drinks/drinks_index',drink: @drink,drinks: @drinks,title: @title%>

app/views/users/show.html.erb
<% provide(:title,"My page")%>
  <div class="user-profile">
    <div class="follow-user">
      <h2 class="user-profile-name"><%= @user.nickname %></h2>
      <% if current_user != @user %>
        <div id="follow_form">
        <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
        <% else %>
          <%= render 'follow' %>
        <% end %>
        </div>
      <% end %>

      <% if current_user == @user%>
        <div class="user-account-config">
          <%= link_to user_config_path do%>
            <i class="fas fa-cog"></i>
          <% end %>
        </div>
      <% end %>
    </div>


  <%if @user.image.attached? %>
    <h2><%= image_tag @user.image.variant(resize: '100x100'),class: 'user-profile-img' %></h2>
  <% else %>
    <img src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YnJlYXV0aWZ1bCUyMGdpcmx8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60" class= 'user-profile-img'>
  <% end %>
  </div> 

      <div class="user-edit">
      <% if current_user?(@user) %>
      <i class="fas fa-user-edit"></i><%= link_to "プロフィールを編集",edit_user_path(@user)%>  
      <% end %>
    </div>




<div class="user-info">
  <div class="user-like-post">
    <%= link_to "#{@user.nickname}がいいねした投稿",user_likes_path(@user.id)%>
  </div>
  <div class="purchase-record">
    <%= link_to  "#{@user.nickname}の購入履歴", "/user/purchase_record" %>
  </div>
  <% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

</div>

<%= render 'drinks/drinks_index',drink: @drink,drinks: @drinks,title: @title%>

app/views/users/show_follow.html.erb
<% @users.each do |user|%>
  <div class="user-follow">
    <%if user.image.attached?%>
      <%=image_tag user.image.variant(resize: '60x60') ,class: "user-follow-img" %>
    <% else %>
    <img src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YnJlYXV0aWZ1bCUyMGdpcmx8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60" class= "user-follow-img" >
    <% end %>
    <div class="nickname-follow">
       <%=link_to user.nickname,user_path(user.id)%>
    </div>
  </div>

<% end %>

app/views/users/thanks.html.erb
<%= @user %>様。貴重なご意見ありがとうございます。
弊社スタッフ一同(俺だけだけど。)さらなる改善に努めて参ります。
<%= link_to "トップページへもどる" root_path%>