config/routes.rb
Rails.application.routes.draw do

  root to: 'drinks#index'
  get    '/login',   to: 'sessions#new'
  post    '/users/auth/:provider/callback',to: 'sessions#create'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # static_pagesのルーティング
  get    '/contact',   to: 'static_pages#contact'
  get    '/about_coffee_passport', to: 'static_pages#about_coffee_passport'
  
  get 'user/config', to: 'users#config'   ,as: 'user_config'
  get 'user/likes/:id',  to: 'users#likes',as: 'user_likes'
  get 'user/purchase_record',to: 'users#purchase_record'
  post 'users/guest_sign_in',to: 'users#new_guest'
  resources :users do
    member do
      get :following,:followers
      # memberメソッドを使うと
      # ユーザーidが含まれてるURlを扱うようになる
    end
  end
  get 'drinks/searchingform', to: 'drinks#show_searching_form'
  get '/drinks/searchdrink',  to: 'drinks#search_drink'
  get '/drink/hashtag/:name', to: "drinks#hashtag"
  resources :drinks, only: [:index,:new,:show,:create,:destroy] do
    collection do
      get 'search'
    end

    resources :comments,only: [:create,:destroy]
    # あるツイートに対してのコメントと言う
    # 親子関係を表現したパスが、コメント投稿に必要なリクエストの
    # パスになります
    
    resources :trades,only: [:index,:new,:create]
  end

  namespace :api, format: 'json' do
    resources :drinks, only: [:index,:show]
  end

  namespace :api, { format: 'json' } do
    resources :likes, only: [:index, :create, :destroy]
  end


  post '/drinks/:id/trades/new', to: 'trades#create'
  resources :relationships, only: [:create,:destroy]
  post 'like/:drink_id' ,to: 'likes#like', as: 'like'
  delete 'like/:drink_id',to: 'likes#unlike', as: 'unlike'
  resources :account_activations, only: [:edit]
  get '/buy', to: 'sold_drinks#index'
  get '/sort_cheap_order', to: "sold_drinks#sort_cheap_order"
  get '/sort_often_purchased_order', to: "sold_drinks#sort_often_purchased_order"
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_errors_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
    <%= link_to "お問い合せ", "/contact"%>
  </div>
  <div>
    <%= link_to "私たちについて", "#"%>
  </div>
  <div>
    <%= link_to "コーヒーをもっと知る", ""%>
  </div>
  <div>
    <%= link_to "Coffee Passport とは", "/about_coffee_passport"%>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="slideshow">
  <div class="registration-main" >

  <%= form_with model: @user, local: true do |f| %>

  <div class='form-wrap'>
    <div class='form-header'>
    <% if current_user %>
       <h1 class='form-header-text'>プロフィール</h1>
    <% else %>
       <h1 class='form-header-text'>会員情報入力</h1>
    <% end %>
    </div>
      <% flash.each do |message_type, message| %>
        <div class="alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= render 'shared/error_messages', object: f.object %>
  
    <div class="form-groups">
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">ニックネーム</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) セイレーン", maxlength:"40" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">プロフィール画像を設定</label>
          <span class="indispensable">任意</span>
        </div>
        <%= f.file_field :image, class:"input-default" %>
        <div id="image-list"></div>
      </div>
      <% unless current_user && logged_in?%>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">メールアドレス</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">パスワード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
        <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">パスワード(確認)</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
      </div>
      <% end %>
    </div>

    <div class='register-btn'>
      <% if current_user && logged_in? %>
        <%= f.submit "更新",class:"register-red-btn"%>
      <% else %>
        <%= f.submit "会員登録" ,class:"register-red-btn" %>
      <% end %>
    </div>

    <% unless current_user?(@user) %>
      <div class="signin">
        <p>アカウントをお持ちですか？</p>
        <%=link_to "ログインする",login_path, class: "signin-path"%>
      </div>
    <% end %>

    <p class='register-info'>本人情報の登録について</p>

  </div>

  <% end %>
  </div>

</div>

app/views/shared/_header.html.erb
  <div class = "header",id="slideshow">

      <%= link_to root_path  do %> 
        <%= image_tag 'logo.png',class: "logo" %> 
      <% end %>

    <% unless logged_in? %>
      <h3 class="header-text">Here your Coffee Passport is.</h3>
    <% end %>
  
    
    <% if current_user%>
      <%= link_to user_path(current_user) do%>
      <% if current_user.image.attached?%>
        <%= image_tag current_user.image.variant(resize: '100x100'),class: 'user-img' %>
      <% else %>
        <img src="https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YnJlYXV0aWZ1bCUyMGdpcmx8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60" class= 'user-img'>
      <% end %>
    <% end %>

    <div class="header-nav">
        <div class = "header-user-name">
          <i class="fas fa-user"></i><a class = "h-user-name"><%= link_to current_user.nickname,user_path(current_user) %></a>
        </div>
    <% end %>  


        <% if current_user  %>
          <div class="post">
            <i class="fas fa-pen-alt"></i><%= link_to "投稿する", new_drink_path %>
          </div>
          <div class="buy-form">
            <i class="fas fa-mug-hot"></i><%= link_to "商品を購入",'/buy', id: "buy-path"%>
          </div>
          <div class="searching-link">
            <i class="fas fa-search"></i><%= link_to "検索" , drinks_searchingform_path%>
          </div>

        <% end %>

    </div>
  </div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<%# メモ化 %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>